-- Seed heavy equipment inventory from yard equipment list
INSERT INTO "Equipment" (
    "id",
    "name",
    "modelNumber",
    "serialNumber",
    "tag",
    "manufacturer",
    "siteId",
    "maintenanceSchedule",
    "costAtPurchase",
    "dateOfPurchase",
    "inspectionSubmissionIds",
    "createdAt",
    "updatedAt"
) VALUES
    (
        'eq-inv-jlg-600s',
        'Telescopic Boom Lift',
        '600S 4WD',
        NULL,
        NULL,
        'JLG',
        NULL,
        'monthly',
        18000.00,
        TIMESTAMP '2008-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'eq-inv-skyjack-sjiii-4632',
        'Electric Scissor Lift',
        'SJIII 4632',
        NULL,
        NULL,
        'Skyjack',
        NULL,
        'monthly',
        4000.00,
        TIMESTAMP '2017-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'eq-inv-genie-s60',
        'Telescopic Boom Lift',
        'S60 4WD',
        NULL,
        NULL,
        'Genie',
        NULL,
        'monthly',
        24000.00,
        TIMESTAMP '2009-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'eq-inv-bobcat-e55',
        'Mini Excavator',
        'E55',
        NULL,
        NULL,
        'Bobcat',
        NULL,
        'monthly',
        28000.00,
        TIMESTAMP '2017-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'eq-inv-genie-gth-1056',
        'Telehandler 10,000#',
        'GTH-1056',
        NULL,
        NULL,
        'Genie',
        NULL,
        'monthly',
        45000.00,
        TIMESTAMP '2008-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'eq-inv-genie-z60-34',
        'Articulating Boom Lift',
        'Z60-34 4WD',
        NULL,
        NULL,
        'Genie',
        NULL,
        'monthly',
        24000.00,
        TIMESTAMP '2013-01-01 00:00:00',
        ARRAY[]::TEXT[],
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT ("id") DO NOTHING;
